# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 2.8.0
maven_group = com.denisnumb.discord_chat_mod
archives_name = discord_chat_mod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.8

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.136.1+1.21.8
neoforge_version = 21.8.52
