name: Feature Request
description: Suggest a new feature or improvement to an existing one
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Description of functionality
      description: >
        Describe what you would like to add/change in the mod
    validations:
      required: true
