name: ❓ Question
description: Ask a question related to the project, its usage or architecture
labels: question
body:
  - type: textarea
    attributes:
      label: Question text
      description: >
        Text of your question
