name: Question
description: Ask a question related to the project, its usage or architecture
labels: question
body:
 - type: textarea
    attributes:
      label: Question text
      description: >
        Describe what you would like to add/change in the mod
    validations:
      required: true
