name: Just Question
description: Ask a question related to the project, its usage or architecture
labels: question
body:
 - type: textarea
    attributes:
      description: >
        Text of your question
    validations:
      required: true
