plugins {
    id 'com.gradleup.shadow'
}

loom {
    forge {
        mixinConfig "discord_chat_mod.mixins.json", "discord_chat_mod.forge.mixins.json"
    }
}


architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')

    shadowBundle(implementation("net.dv8tion:JDA:6.1.1")) {transitive = false }
    shadowBundle(implementation("com.squareup.okhttp3:okhttp:4.12.0")) {transitive = false }
    shadowBundle(implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.0")) {transitive = false }
    shadowBundle(implementation("com.squareup.okio:okio:3.9.1")) {transitive = false }
    shadowBundle(implementation("com.neovisionaries:nv-websocket-client:2.14")) {transitive = false }
    shadowBundle(implementation("net.sf.trove4j:trove4j:3.0.3")) {transitive = false }
    shadowBundle(implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")) {transitive = false }
    shadowBundle(implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")) {transitive = false }
    shadowBundle(implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")) {transitive = false }
    shadowBundle(implementation("org.apache.commons:commons-collections4:4.4")) {transitive = false }
    shadowBundle(implementation("org.json:json:20231013")) { transitive = false }
    shadowBundle(implementation("org.jsoup:jsoup:1.17.2")) { transitive = false }
    shadowBundle(implementation(files("../libs/emoji-java-5.1.1.jar")))
    shadowBundle(implementation("com.electronwill.night-config:core:3.8.3")) { transitive = false }
    shadowBundle(implementation("com.electronwill.night-config:toml:3.8.3")) { transitive = false }
    shadowBundle(implementation("com.twelvemonkeys.imageio:imageio-webp:3.12.0")) { transitive = false }
    shadowBundle(implementation("com.twelvemonkeys.imageio:imageio-core:3.12.0"))
    compileOnly("org.apache.logging.log4j:log4j-core:2.20.0")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.5.0"))

    minecraftRuntimeLibraries "net.dv8tion:JDA:6.1.1"
    minecraftRuntimeLibraries "org.json:json:20231013"
    minecraftRuntimeLibraries "com.twelvemonkeys.imageio:imageio-webp:3.12.0"
    minecraftRuntimeLibraries "com.twelvemonkeys.imageio:imageio-core:3.12.0"
    minecraftRuntimeLibraries(files("../libs/emoji-java-5.1.1.jar"))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    mergeServiceFiles()

    relocate("com.squareup", "com.shadow.com.squareup")
    relocate("com.neovisionaries", "com.shadow.com.neovisionaries")
    relocate("com.fasterxml", "com.shadow.com.fasterxml")
    relocate("net.dv8tion", "com.shadow.net.dv8tion")
    relocate("org.apache.commons", "com.shadow.org.apache.commons")
    relocate("gnu.trove", "com.shadow.gnu.trove")
    relocate("kotlin", "com.shadow.kotlin")
    relocate("okhttp3", "com.shadow.okhttp3")
    relocate("okio", "com.shadow.okio")
    relocate("com.vdurmont", "com.shadow.com.vdurmont")
    relocate("org.json", "com.shadow.org.json")
    relocate("org.jsoup", "com.shadow.org.jsoup")
    relocate("com.electronwill", "com.shadow.com.electronwill")
    relocate("com.twelvemonkeys", "com.shadow.com.twelvemonkeys")
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
