modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/denisnumb/discord-minecraft-chat/issues"
license = "All Rights Reserved"

[[mods]]
modId = "discord_chat_mod"
version = "${version}"
displayName = "Discord & Chat Images"
authors = "denisnumb"
description = '''
Mod for combining minecraft chat with discord chat and chat image displaying
'''
logoFile= "logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/discord-chat-connect"

[[dependencies.discord_chat_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discord_chat_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "discord_chat_mod.neoforge.mixins.json"

[[mixins]]
config = "discord_chat_mod.mixins.json"
